version: "2"

services:
  page-sample:
    image: trinitronx/python-simplehttpserver
    restart: always
    ports:
      - "8000:8080"
    volumes:
      - "./page-sample:/var/www"

  redis:
    image: redis:5.0.4
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_PASSWORD: pgPas5VeryHard1
      PGDATA: "/app/nav-tracking/data/postgres"
    ports:
      - "5432:5432"
    volumes:
      - './data/postgres:/app/nav-tracking/data/postgres'

  rails:
    build: ./nav-tracking-rails
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_MAX_THREADS: 5
      PGPASSWORD: pgPas5VeryHard1
      PGHOST: postgres
      REDISHOST: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  sidekiq:
    build: ./nav-tracking-rails
    restart: always
    command: bash bin/start-sidekiq
    environment:
      PGPASSWORD: pgPas5VeryHard1
      PGHOST: postgres
      REDISHOST: redis://redis:6379/0
    depends_on:
      - rails
      - redis

  tasks:
    build: ./nav-tracking-rails
    restart: always
    command: bash bin/start-tasks
    environment:
      PGPASSWORD: pgPas5VeryHard1
      PGHOST: postgres
      REDISHOST: redis://redis:6379/0
    depends_on:
      - rails
      - sidekiq
      - redis
